[package]
name = "day1"
version = "0.1.0"
edition = "2021"
authors = ["Antoine Toussaint <antoine.toussaint2002@gmail.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
